/// xazz-compiler/src/emitter.rs — Rust 코드 에밋 (Transpiler Layer) v0.16
///
/// .xzz 스크립트 → 독립 실행 가능한 Rust + Polars 소스 코드 생성기.
///
/// [v0.16 변경사항]
///   - BoolLit 지원 (to_typed_polars_expr)
///   - Count(None) / Count(Some(col)) 구분
///   - 신규 연산자 코드 생성:
///       GroupBy + 집계 연산자 → .group_by([...]).agg([...]) 페어링
///       OrderBy → .sort([...], SortMultipleOptions)
///       Take → .limit(n)
///       DropNull → .drop_nulls(Some(vec![...]))
///       FillNull → .with_columns([...fill_null(...)])
///   - validate_op_columns: 신규 컬럼 인수 연산자 스키마 검증 추가
///   - Join 연산자 코드 생성: .join(..., JoinArgs::new(JoinType::...))
///   - WithColumn 연산자 코드 생성: .with_columns([expr.alias("name")])
///   - 산술 연산자 to_typed_polars_expr: add/sub/mul/div
use std::collections::HashMap;
use std::fs;

use crate::ast::{
    BinOpKind, Expr, FillNullValue, LayerKind, PipelineOp, PipelineSource, Program, Stmt,
    TrainConfig,
};
use crate::{Codegen, Lexer, Parser, StructField};

// ─────────────────────────────────────────────────────────────────────────────
// ── 공개 진입점 ───────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// .xzz 파일을 독립 실행 가능한 Rust 소스 코드로 변환한다.
pub fn emit_rust(
    source_path: &str,
    out_path: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // ── Step 1: 소스 파일 읽기 ───────────────────────────────────────────────
    let source = fs::read_to_string(source_path)
        .map_err(|e| format!("IO 에러: 파일 읽기 실패 '{}' — {}", source_path, e))?;

    // ── Step 2: 렉서 ────────────────────────────────────────────────────────
    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize().map_err(|e| format!("{}", e))?;

    // ── Step 3: 파서 ────────────────────────────────────────────────────────
    let mut parser = Parser::new(tokens);
    let program = parser.parse().map_err(|e| format!("{}", e))?;

    // ── Step 4: 스키마 검증 + Rust 코드 생성 ────────────────────────────────
    let rust_code = generate_rust_src(&program, source_path)?;

    // ── Step 5: 출력 ────────────────────────────────────────────────────────
    match out_path {
        Some(path) => {
            fs::write(path, &rust_code)
                .map_err(|e| format!("IO 에러: 출력 파일 쓰기 실패 '{}' — {}", path, e))?;

            println!("✅  emit rust 완료 → {}", path);
            println!();
            println!("─── 실행 방법 ──────────────────────────────────────────────────");
            println!("  1) 새 Rust 프로젝트 생성:");
            println!("       cargo new my_analysis && cd my_analysis");
            println!("  2) Cargo.toml 에 의존성 추가:");
            println!(
                "       polars      = {{ version = \"0.53\", features = [\"lazy\", \"csv\"] }}"
            );
            println!("       encoding_rs = \"0.8\"");
            println!("  3) {} 를 src/main.rs 로 복사 후 실행:", path);
            println!("       cargo run");
            println!("────────────────────────────────────────────────────────────────");
        }
        None => println!("{}", rust_code),
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 내부: AST → Rust 소스 문자열 생성 ─────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn generate_rust_src(
    program: &Program,
    source_path: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    // ── 전역 스키마 맵 구축 ──────────────────────────────────────────────────
    let mut schema_map: HashMap<String, Vec<StructField>> = HashMap::new();
    for stmt in &program.stmts {
        if let Stmt::TypeDecl { name, fields } = stmt {
            schema_map.insert(name.clone(), fields.clone());
        }
    }

    let mut out = String::new();

    // 파일 헤더
    out.push_str("// ═══════════════════════════════════════════════════════════════\n");
    out.push_str("// Auto-generated by xazzLang `emit rust`\n");
    out.push_str(&format!("// Source: {}\n", source_path));
    out.push_str("//\n");
    out.push_str("// [필요한 Cargo.toml 의존성]\n");
    out.push_str("//   polars      = { version = \"0.53\", features = [\"lazy\", \"csv\"] }\n");
    out.push_str("//   encoding_rs = \"0.8\"\n");
    if program_has_dl(program) {
        out.push_str("//   burn        = { version = \"0.21\", default-features = false, features = [\"std\", \"autodiff\"] }\n");
        out.push_str("//   burn-ndarray = { version = \"0.21\", default-features = false, features = [\"std\", \"burn-autodiff\"] }\n");
    }
    out.push_str("// ═══════════════════════════════════════════════════════════════\n\n");

    // 임포트
    out.push_str("use polars::prelude::*;\n");
    out.push_str("use encoding_rs::EUC_KR;\n");
    out.push_str("use std::io::Cursor;\n\n");

    if program_has_dl(program) {
        out.push_str(&emit_burn_imports());
        out.push('\n');
    }

    // CSV 로더 헬퍼
    out.push_str(&emit_csv_loader_fn());
    out.push('\n');

    // 딥러닝 (Burn) 모델 정의 + 학습 헬퍼
    if program_has_dl(program) {
        for stmt in &program.stmts {
            if let Stmt::ModelDecl { name, layers } = stmt {
                out.push_str(&emit_dl_model_struct(name, layers));
            }
        }
        out.push_str(&emit_extract_xy_fn());
        out.push('\n');
    }

    // fn main()
    out.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");

    // TypeDecl → 스키마 주석 블록
    let has_schemas = program
        .stmts
        .iter()
        .any(|s| matches!(s, Stmt::TypeDecl { .. }));
    if has_schemas {
        out.push_str("    // ── xazzLang Schema Definitions (참조용 주석) ─────────────────────\n");
        for stmt in &program.stmts {
            if let Stmt::TypeDecl { name, fields } = stmt {
                out.push_str(&format!("    // type {} = {{\n", name));
                for f in fields {
                    out.push_str(&format!("    //   {:<14}: {}\n", f.name, f.field_type));
                }
                out.push_str("    // }\n");
            }
        }
        out.push_str(
            "    // ──────────────────────────────────────────────────────────────────\n\n",
        );
    }

    // 변수별 스키마 추적
    let mut var_col_types: HashMap<String, HashMap<String, String>> = HashMap::new();

    // VarDecl → LazyFrame 파이프라인
    for stmt in &program.stmts {
        if let Stmt::VarDecl {
            var_name,
            is_mut,
            source,
            ops,
        } = stmt
        {
            let mut_kw = if *is_mut { "mut " } else { "" };

            // 활성 컬럼 타입 맵 결정
            let col_types: HashMap<String, String> = match source {
                PipelineSource::Load { schema_name, .. } => schema_map
                    .get(schema_name)
                    .map(|fields| {
                        fields
                            .iter()
                            .map(|f| (f.name.clone(), f.field_type.clone()))
                            .collect()
                    })
                    .unwrap_or_default(),
                PipelineSource::VarRef(src_var) => var_col_types
                    .get(src_var.as_str())
                    .cloned()
                    .unwrap_or_default(),
            };

            // 스키마 검증
            if !col_types.is_empty() {
                for op in ops {
                    validate_op_columns(op, &col_types, &var_col_types, source_path)?;
                }
            }

            // 코드 생성 헤더
            out.push_str(&format!(
                "    // ── Pipeline: {}v {} ──────────────────────────────────────────\n",
                mut_kw, var_name
            ));

            // 소스 결정
            match source {
                PipelineSource::Load {
                    file_path,
                    schema_name,
                } => {
                    out.push_str(&format!(
                        "    // load(\"{}\") :: {}\n",
                        file_path, schema_name
                    ));
                    out.push_str(&format!(
                        "    let {}{} = load_csv(\"{}\")? // :: {}\n",
                        mut_kw, var_name, file_path, schema_name
                    ));
                    out.push_str("        .lazy()\n");
                }
                PipelineSource::VarRef(src_var) => {
                    out.push_str(&format!(
                        "    let {}{} = {}.clone().lazy()\n",
                        mut_kw, var_name, src_var
                    ));
                }
            }

            // ── 파이프라인 연산자 체이닝 ─────────────────────────────────────
            // GroupBy+agg 패턴: GroupBy를 저장해 두었다가 다음 집계 연산자와 합쳐 출력
            let mut has_count = false;
            let mut pending_group_col: Option<String> = None;

            for op in ops {
                match op {
                    PipelineOp::Filter(expr) => {
                        let polars_expr = to_typed_polars_expr(expr, &col_types);
                        out.push_str(&format!(
                            "        .filter({})  // |> filter({})\n",
                            polars_expr,
                            Codegen::expr_to_xzz(expr)
                        ));
                    }
                    PipelineOp::Select(cols) => {
                        let polars_cols: Vec<String> =
                            cols.iter().map(|c| format!("col(\"{}\")", c)).collect();
                        out.push_str(&format!(
                            "        .select([{}])  // |> select([{}])\n",
                            polars_cols.join(", "),
                            cols.join(", ")
                        ));
                    }
                    PipelineOp::Count(None) => {
                        // count (no arg): 행 수 출력용 플래그만 설정
                        has_count = true;
                    }

                    // ── GroupBy 저장 ───────────────────────────────────────────
                    PipelineOp::GroupBy(group_col) => {
                        pending_group_col = Some(group_col.clone());
                    }

                    // ── 집계 연산자: GroupBy와 함께 또는 단독 ─────────────────
                    PipelineOp::Count(Some(agg_col)) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").count()])  // |> groupBy(\"{}\") |> count(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").count()])  // |> count(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Sum(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").sum()])  // |> groupBy(\"{}\") |> sum(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").sum()])  // |> sum(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Mean(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").mean()])  // |> groupBy(\"{}\") |> mean(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").mean()])  // |> mean(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Min(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").min()])  // |> groupBy(\"{}\") |> min(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").min()])  // |> min(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Max(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").max()])  // |> groupBy(\"{}\") |> max(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").max()])  // |> max(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }

                    // ── 정렬 / 슬라이싱 ────────────────────────────────────────
                    PipelineOp::OrderBy {
                        col: sort_col,
                        desc,
                    } => {
                        out.push_str(&format!(
                            "        .sort([\"{}\"], SortMultipleOptions::default().with_order_descending({}))  // |> orderBy(\"{}\", desc: {})\n",
                            sort_col, desc, sort_col, desc
                        ));
                    }
                    PipelineOp::Take(n) => {
                        out.push_str(&format!("        .limit({})  // |> take({})\n", n, n));
                    }

                    // ── Null 처리 ──────────────────────────────────────────────
                    PipelineOp::DropNull(drop_col) => {
                        out.push_str(&format!(
                            "        .drop_nulls(Some(vec![col(\"{}\")]))  // |> dropNull(\"{}\")\n",
                            drop_col, drop_col
                        ));
                    }
                    PipelineOp::FillNull {
                        col: fill_col,
                        value,
                    } => {
                        let lit_str = match value {
                            FillNullValue::Mean => format!("col(\"{}\").mean()", fill_col),
                            FillNullValue::Median => format!("col(\"{}\").median()", fill_col),
                            FillNullValue::Zero => "lit(0)".to_string(),
                            FillNullValue::Int(n) => format!("lit({}i64)", n),
                            FillNullValue::Float(f) => format!("lit({}f64)", f),
                            FillNullValue::Str(s) => format!("lit(\"{}\")", s),
                        };
                        out.push_str(&format!(
                            "        .with_columns([col(\"{}\").fill_null({})])  // |> fillNull(\"{}\", ...)\n",
                            fill_col, lit_str, fill_col
                        ));
                    }

                    // ── v0.16+ / v0.21 Join ────────────────────────────────────
                    PipelineOp::Join {
                        other,
                        left_on,
                        right_on,
                        how,
                    } => {
                        let left_cols: Vec<String> =
                            left_on.iter().map(|k| format!("col(\"{}\")", k)).collect();
                        let right_cols: Vec<String> =
                            right_on.iter().map(|k| format!("col(\"{}\")", k)).collect();
                        out.push_str(&format!(
                            "        .join(\n            {}.clone().lazy(),\n            [{}],\n            [{}],\n            JoinArgs::new({}),\n        )  // |> join({}, left_on: {:?}, right_on: {:?})\n",
                            other,
                            left_cols.join(", "),
                            right_cols.join(", "),
                            how.as_polars_str(),
                            other,
                            left_on,
                            right_on
                        ));
                    }

                    // ── v0.16+ WithColumn ──────────────────────────────────────
                    PipelineOp::WithColumn {
                        name: col_name,
                        expr,
                    } => {
                        let polars_expr = to_typed_polars_expr(expr, &col_types);
                        out.push_str(&format!(
                            "        .with_columns([{}.alias(\"{}\")])  // |> withColumn(\"{}\", {})\n",
                            polars_expr,
                            col_name,
                            col_name,
                            Codegen::expr_to_xzz(expr)
                        ));
                    }

                    // ── Chart: emitter 미지원 (런타임에서만 처리) ──────────────
                    PipelineOp::Chart(config) => {
                        out.push_str(&format!(
                            "        // |> chart {{ type: {} }}  →  [xazz:chart] JSON 출력\n",
                            config.chart_type.as_str()
                        ));
                    }

                    // ── v0.20 Cast ─────────────────────────────────────────────
                    PipelineOp::Cast {
                        col: cast_col,
                        to_type,
                    } => {
                        let polars_type = match to_type.as_str() {
                            "float" => "DataType::Float64",
                            "int" => "DataType::Int64",
                            "str" => "DataType::String",
                            "bool" => "DataType::Boolean",
                            other => other,
                        };
                        out.push_str(&format!(
                            "        .with_columns([col(\"{}\").cast({})])  // |> cast(\"{}\", \"{}\")\n",
                            cast_col, polars_type, cast_col, to_type
                        ));
                    }

                    // ── Rename ─────────────────────────────────────────────────
                    PipelineOp::Rename { old_name, new_name } => {
                        out.push_str(&format!(
                            "        .rename([\"{}\"], [\"{}\"], false)  // |> rename(\"{}\", \"{}\")\n",
                            old_name, new_name, old_name, new_name
                        ));
                    }

                    // ── Replace ────────────────────────────────────────────────
                    PipelineOp::Replace {
                        col: rep_col,
                        from,
                        to,
                    } => {
                        out.push_str(&format!(
                            "        .with_columns([col(\"{}\").str().replace(lit(\"{}\"), lit(\"{}\"), false).alias(\"{}\")])  // |> replace(\"{}\", \"{}\", \"{}\")\n",
                            rep_col, from, to, rep_col, rep_col, from, to
                        ));
                    }

                    // ── v0.22 sample(n) / sample(n, seed: 42) ──────────────────
                    PipelineOp::Sample { n, seed } => match seed {
                        Some(s) => {
                            out.push_str(&format!(
                                "        .collect()?.sample_n_literal({}, false, false, Some({}))?.lazy()  // |> sample({}, seed: {})\n",
                                n, s, n, s
                            ));
                        }
                        None => {
                            out.push_str(&format!(
                                "        .collect()?.sample_n_literal({}, false, false, None)?.lazy()  // |> sample({})\n",
                                n, n
                            ));
                        }
                    },

                    // ── v0.22 median / variance / std 집계 ─────────────────────
                    PipelineOp::Median(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").median()])  // |> groupBy(\"{}\") |> median(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").median()])  // |> median(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Variance(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").var(1)])  // |> groupBy(\"{}\") |> variance(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").var(1)])  // |> variance(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    PipelineOp::Std(agg_col) => {
                        if let Some(gc) = pending_group_col.take() {
                            out.push_str(&format!(
                                "        .group_by([col(\"{}\")])\n        .agg([col(\"{}\").std(1)])  // |> groupBy(\"{}\") |> std(\"{}\")\n",
                                gc, agg_col, gc, agg_col
                            ));
                        } else {
                            out.push_str(&format!(
                                "        .select([col(\"{}\").std(1)])  // |> std(\"{}\")\n",
                                agg_col, agg_col
                            ));
                        }
                    }
                    // ── v0.5 딥러닝 연산자: emit rust 에서는 런타임 학습/예측으로 안내 ──
                    PipelineOp::Train { model_name, config } => {
                        out.push_str(&format!(
                            "        // |> train({}, target: \"{}\", epochs: {})  → xazz 실행 시 Burn 학습 수행\n",
                            model_name, config.target, config.epochs
                        ));
                    }
                    PipelineOp::Predict { model_var, as_col } => {
                        let as_str = as_col
                            .as_deref()
                            .map(|c| format!(", as: \"{}\"", c))
                            .unwrap_or_default();
                        out.push_str(&format!(
                            "        // |> predict({}{})  → 예측 컬럼 추가 (xazz 실행 시)\n",
                            model_var, as_str
                        ));
                    }
                    // ── v0.6 withDp — emit rust 에서는 런타임 DP 주입으로 안내 ──
                    PipelineOp::WithDp(args) => {
                        out.push_str(&format!(
                            "        // |> withDp(epsilon: {}, mechanism: {})  → xazz 실행 시 DP 노이즈 주입\n",
                            args.epsilon,
                            args.mechanism.as_str()
                        ));
                    }
                }
            }

            // collect
            out.push_str("        .collect()?;\n");

            // 결과 출력
            if has_count {
                out.push_str(&format!(
                    "    println!(\"[{}] count = {{}}\", {}.height());\n",
                    var_name, var_name
                ));
            } else {
                out.push_str(&format!(
                    "    println!(\"[{}]\\n{{}}\", {});\n",
                    var_name, var_name
                ));
            }
            out.push('\n');

            if !col_types.is_empty() {
                var_col_types.insert(var_name.clone(), col_types);
            }
        }
    }

    // 딥러닝 (Burn) 학습 문 실행
    for stmt in &program.stmts {
        if let Stmt::TrainStmt {
            source_var,
            model_name,
            config,
        } = stmt
        {
            out.push_str(&emit_dl_train_call(source_var, model_name, config));
        }
    }

    out.push_str("    Ok(())\n");
    out.push_str("}\n");

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 딥러닝 (Burn) 코드 생성 (v0.4) ─────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// 스크립트에 DL 구문(ModelDecl / TrainStmt)이 포함되어 있는지 확인한다.
fn program_has_dl(program: &Program) -> bool {
    program
        .stmts
        .iter()
        .any(|s| matches!(s, Stmt::ModelDecl { .. } | Stmt::TrainStmt { .. }))
}

/// Burn 임포트 블록.
fn emit_burn_imports() -> String {
    r#"use burn::{
    backend::Autodiff,
    module::Module,
    nn::{Linear, LinearConfig},
    optim::{AdamConfig, GradientsParams, Optimizer},
    record::{FullPrecisionSettings, PrettyJsonFileRecorder},
    tensor::{
        Device, Tensor, TensorData,
        activation::{relu, sigmoid, softmax, tanh},
        backend::Backend,
    },
};
use burn_ndarray::NdArray;

type TrainBackend = Autodiff<NdArray<f32>>;
"#
    .to_string()
}

/// DSL 레이어 체인을 Dense (units, activation) 스펙 목록으로 정규화한다.
/// 활성화 호출은 바로 앞선 Dense 레이어에 귀속된다 (dl.rs 와 동일한 시맨틱).
fn dl_dense_specs(layers: &[LayerKind]) -> Vec<(usize, String)> {
    let mut specs: Vec<(usize, String)> = Vec::new();
    for layer in layers {
        match layer {
            LayerKind::Dense(n) if *n > 0 => specs.push((*n, String::from("None"))),
            LayerKind::Dense(_) => {}
            LayerKind::ReLU => set_dl_act(&mut specs, "relu"),
            LayerKind::Sigmoid => set_dl_act(&mut specs, "sigmoid"),
            LayerKind::Tanh => set_dl_act(&mut specs, "tanh"),
            LayerKind::Softmax => set_dl_act(&mut specs, "softmax"),
            LayerKind::Dropout(_) | LayerKind::BatchNorm => {}
        }
    }
    specs
}

fn set_dl_act(specs: &mut [(usize, String)], act: &str) {
    if let Some(last) = specs.last_mut() {
        last.1 = act.to_string();
    }
}

/// `model <Name> { ... }` → Burn nn 모듈 구조체 + new() + forward().
fn emit_dl_model_struct(name: &str, layers: &[LayerKind]) -> String {
    let specs = dl_dense_specs(layers);
    if specs.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str(&format!(
        "#[derive(Module, Debug)]\nstruct {}<B: Backend> {{\n",
        name
    ));
    for (i, (units, _)) in specs.iter().enumerate() {
        out.push_str(&format!("    layer{i}: Linear<B>,  // Dense({units})\n"));
    }
    out.push_str("}\n\n");

    out.push_str(&format!(
        "impl<B: Backend> {name}<B> {{\n    fn new(device: &Device<B>, input_dim: usize) -> Self {{\n        Self {{\n"
    ));
    let mut cur = "input_dim".to_string();
    for (i, (units, _)) in specs.iter().enumerate() {
        out.push_str(&format!(
            "            layer{i}: LinearConfig::new({cur}, {units}).init(device),\n"
        ));
        cur = units.to_string();
    }
    out.push_str("        }\n    }\n\n");

    out.push_str(
        "    fn forward<const D: usize>(&self, x: Tensor<B, D>) -> Tensor<B, D> {\n        let x = x;\n",
    );
    for (i, (_, act)) in specs.iter().enumerate() {
        out.push_str(&format!("        let x = self.layer{i}.forward(x);\n"));
        match act.as_str() {
            "relu" => out.push_str("        let x = relu(x);\n"),
            "sigmoid" => out.push_str("        let x = sigmoid(x);\n"),
            "tanh" => out.push_str("        let x = tanh(x);\n"),
            "softmax" => out.push_str("        let x = softmax(x, 1);\n"),
            _ => {}
        }
    }
    out.push_str("        x\n    }\n}\n\n");

    out
}

/// 컬럼 → f32 텐서 데이터 추출 헬퍼 (Polars DataFrame → (x_flat, y_flat, feature_count)).
fn emit_extract_xy_fn() -> String {
    r#"/// 타겟을 제외한 숫자형 컬럼을 특성으로, 타겟 컬럼을 라벨로 추출한다.
fn extract_xy(
    df: &DataFrame,
    target: &str,
) -> Result<(Vec<f32>, Vec<f32>, usize), Box<dyn std::error::Error>> {
    let names = df.get_column_names();
    let mut features: Vec<String> = Vec::new();
    for name in names {
        if name.as_str() == target {
            continue;
        }
        if let Ok(col) = df.column(name.as_str()) {
            if matches!(
                col.dtype(),
                DataType::Float64
                    | DataType::Float32
                    | DataType::Int64
                    | DataType::Int32
                    | DataType::Int16
                    | DataType::Int8
                    | DataType::UInt64
                    | DataType::UInt32
                    | DataType::UInt16
                    | DataType::UInt8
            ) {
                features.push(name.to_string());
            }
        }
    }
    if features.is_empty() {
        return Err("학습 가능한 숫자형 특성 컬럼이 없습니다.".into());
    }
    let n = df.height();
    let mut xs = Vec::with_capacity(n * features.len());
    let mut ys = Vec::with_capacity(n);
    for i in 0..n {
        for f in &features {
            let v = df.column(f)?.get(i).unwrap_or(AnyValue::Float64(f64::NAN));
            xs.push(xz_anyvalue_f32(v));
        }
        let v = df.column(target)?.get(i).unwrap_or(AnyValue::Float64(f64::NAN));
        ys.push(xz_anyvalue_f32(v));
    }
    Ok((xs, ys, features.len()))
}

/// AnyValue → f32 (비숫자는 NaN).
fn xz_anyvalue_f32(v: AnyValue) -> f32 {
    match v {
        AnyValue::Float64(x) => x as f32,
        AnyValue::Float32(x) => x,
        AnyValue::Int64(x) => x as f32,
        AnyValue::Int32(x) => x as f32,
        AnyValue::Int16(x) => x as f32,
        AnyValue::Int8(x) => x as f32,
        AnyValue::UInt64(x) => x as f32,
        AnyValue::UInt32(x) => x as f32,
        AnyValue::UInt16(x) => x as f32,
        AnyValue::UInt8(x) => x as f32,
        _ => f32::NAN,
    }
}

/// 배치를 잘라 (특성 텐서, 라벨 텐서)로 만든다.
fn make_both_tensors(
    xs: &[f32],
    ys: &[f32],
    feature_count: usize,
    start: usize,
    end: usize,
    device: &Device<TrainBackend>,
) -> (Tensor<TrainBackend, 2>, Tensor<TrainBackend, 2>) {
    let b = end - start;
    let mut xv = Vec::with_capacity(b * feature_count);
    let mut yv = Vec::with_capacity(b);
    for i in start..end {
        for j in 0..feature_count {
            xv.push(xs[i * feature_count + j]);
        }
        yv.push(ys[i]);
    }
    let x = Tensor::<TrainBackend, 2>::from_data(TensorData::new(xv, [b, feature_count]), device);
    let y = Tensor::<TrainBackend, 2>::from_data(TensorData::new(yv, [b, 1]), device);
    (x, y)
}
"#
    .to_string()
}

/// `run <src> |> train(<Model>, ...)` → main() 내부 학습 코드 블록.
fn emit_dl_train_call(source_var: &str, model_name: &str, config: &TrainConfig) -> String {
    let target = &config.target;
    let epochs = config.epochs.max(1);
    let lr = config.learning_rate;
    let batch_size = config.batch_size.unwrap_or(32).max(1);
    let val_split = config.validation_split.unwrap_or(0.0).clamp(0.0, 0.9);

    format!(
        r#"    // ── Deep Learning: run {source_var} |> train({model_name}, target: "{target}") ──────
    {{
        let (xs, ys, feature_count) = extract_xy(&{source_var}, "{target}")?;
        let n = ys.len();
        if n == 0 {{
            return Err("학습 데이터가 비어 있습니다.".into());
        }}

        // NaN → 평균 대체 + 표준화 (특성별 z-score)
        let mut fmean = vec![0f64; feature_count];
        let mut fstd = vec![1f64; feature_count];
        for j in 0..feature_count {{
            let (mut s, mut c) = (0f64, 0usize);
            for i in 0..n {{
                let v = xs[i * feature_count + j] as f64;
                if v.is_finite() {{ s += v; c += 1; }}
            }}
            fmean[j] = if c > 0 {{ s / c as f64 }} else {{ 0.0 }};
        }}
        for j in 0..feature_count {{
            let (mut s, mut c) = (0f64, 0usize);
            for i in 0..n {{
                let d = xs[i * feature_count + j] as f64 - fmean[j];
                if d.is_finite() {{ s += d * d; c += 1; }}
            }}
            fstd[j] = if c > 1 {{ (s / (c - 1) as f64).max(1e-8).sqrt() }} else {{ 1.0 }};
        }}
        let xs: Vec<f32> = xs
            .iter()
            .enumerate()
            .map(|(idx, v)| {{
                let row = idx / feature_count;
                let col = idx % feature_count;
                let v = v as f64;
                let v = if !v.is_finite() {{ fmean[col] }} else {{ v }};
                ((v - fmean[col]) / fstd[col]) as f32
            }})
            .collect();
        let tmean: f64 = {{
            let (mut s, mut c) = (0f64, 0usize);
            for &t in &ys {{ if t.is_finite() {{ s += t as f64; c += 1; }} }}
            if c > 0 {{ s / c as f64 }} else {{ 0.0 }}
        }};
        let ys: Vec<f32> = ys
            .iter()
            .map(|&t| if t.is_finite() {{ t as f32 }} else {{ tmean as f32 }})
            .collect();

        let device: Device<TrainBackend> = Default::default();
        let mut model = {model_name}::<TrainBackend>::new(&device, feature_count);
        let mut optim = AdamConfig::new().init::<TrainBackend, _>();

        let train_n = n - ((n as f64 * {val_split}) as usize);
        for epoch in 0..{epochs} {{
            let mut loss_sum = 0f32;
            let mut steps = 0usize;
            for b in 0..((train_n + {batch_size} - 1) / {batch_size}) {{
                let start = b * {batch_size};
                let end = ((b + 1) * {batch_size}).min(train_n);
                let (x, y) = make_both_tensors(&xs, &ys, feature_count, start, end, &device);
                let out = model.forward(x);
                let loss = ((out - y).powf_scalar(2.0)).mean();
                let lv = loss.clone().into_data().to_vec::<f32>().unwrap_or_default()[0];
                let grads = loss.backward();
                let grads = GradientsParams::from_grads(grads, &model);
                model = optim.step({lr}, model, grads);
                loss_sum += lv;
                steps += 1;
            }}
            println!(
                "[Epoch {{epoch:>3}}/{{}}]  train_loss(MSE) = {{:.6}}",
                {epochs},
                if steps > 0 {{ loss_sum / steps as f32 }} else {{ 0.0 }}
            );
        }}

        let valid = model.valid();
        let recorder = PrettyJsonFileRecorder::<FullPrecisionSettings>::new();
        std::fs::create_dir_all("checkpoints")?;
        valid.save_file(&format!("checkpoints/{model_name}"), &recorder)?;
        println!("[xazz] ✅ 체크포인트 저장 → checkpoints/{model_name}.json");
    }}
"#
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 스키마 기반 컬럼명 검증 ────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn validate_op_columns(
    op: &PipelineOp,
    col_types: &HashMap<String, String>,
    var_col_types: &HashMap<String, HashMap<String, String>>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // 컬럼명을 스키마에서 검사하는 내부 헬퍼
    let check_col = |col_name: &str| -> Result<(), Box<dyn std::error::Error>> {
        if !col_types.contains_key(col_name) {
            let available: Vec<&str> = col_types.keys().map(String::as_str).collect();
            let suggestion = find_closest_col(col_name, &available).unwrap_or(col_name);
            return Err(format!(
                "[SchemaError] at {}\n\
                 ─────────────────────────────────────────────\n\
                 Cause   : 선언되지 않은 컬럼이 있습니다.\n\
                 Detail  : column '{}' not found in schema\n\
                 Available: {}\n\
                 → Did you mean: col(\"{}\")",
                source_path,
                col_name,
                available.join(", "),
                suggestion
            )
            .into());
        }
        Ok(())
    };

    match op {
        PipelineOp::Filter(expr) => {
            validate_expr_columns(expr, col_types, source_path)?;
        }
        PipelineOp::Select(cols) => {
            for col_name in cols {
                check_col(col_name.as_str())?;
            }
        }
        // 컬럼 인수가 없는 연산자
        PipelineOp::Count(None) => {}
        PipelineOp::Take(_) => {}
        PipelineOp::Sample { .. } => {}

        // 문자열 컬럼 인수를 갖는 연산자 — 모두 스키마 검증
        PipelineOp::Count(Some(col))
        | PipelineOp::GroupBy(col)
        | PipelineOp::Sum(col)
        | PipelineOp::Mean(col)
        | PipelineOp::Min(col)
        | PipelineOp::Max(col)
        | PipelineOp::Median(col)
        | PipelineOp::Variance(col)
        | PipelineOp::Std(col)
        | PipelineOp::DropNull(col) => {
            check_col(col.as_str())?;
        }
        PipelineOp::OrderBy { col, .. } => {
            check_col(col.as_str())?;
        }
        PipelineOp::FillNull { col, .. } => {
            check_col(col.as_str())?;
        }

        // join: left_on/right_on 컬럼 검증 + other 변수 존재 확인
        PipelineOp::Join {
            other,
            left_on,
            right_on,
            ..
        } => {
            // left_on 키들: 현재 스키마에서 검증
            for key in left_on.iter().chain(right_on.iter()) {
                check_col(key.as_str())?;
            }
            // other 변수 존재 확인
            if !var_col_types.contains_key(other.as_str()) {
                return Err(format!(
                    "[SchemaError] at {}\n\
                     join() 의 대상 변수 '{}' 가 아직 선언되지 않았습니다.\n\
                     → join() 대상 변수를 먼저 파이프라인에서 선언하세요.",
                    source_path, other
                )
                .into());
            }
        }

        // rename: 컬럼 존재 검증
        PipelineOp::Rename { old_name, .. } => {
            check_col(old_name.as_str())?;
        }

        // replace: 컬럼 존재 검증
        PipelineOp::Replace { col, .. } => {
            check_col(col.as_str())?;
        }

        // withColumn: name은 새 컬럼이므로 스키마 검증 생략, expr 내 컬럼만 검증
        PipelineOp::WithColumn { expr, .. } => {
            validate_expr_columns(expr, col_types, source_path)?;
        }

        // Chart: 런타임에서만 처리 (검증 생략)
        PipelineOp::Chart(_) => {}

        // Cast: 컬럼은 DSL 작성자가 보장 (검증 생략)
        PipelineOp::Cast { .. } => {}

        // v0.5 딥러닝 연산자: 모델 변수는 런타임에서 검증 (검증 생략)
        PipelineOp::Train { .. } => {}
        PipelineOp::Predict { .. } => {}

        // v0.6 withDp: 컬럼 인수 없음 — 인수 범위는 파서에서 검증 (검증 생략)
        PipelineOp::WithDp(_) => {}
    }
    Ok(())
}

fn validate_expr_columns(
    expr: &Expr,
    col_types: &HashMap<String, String>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match expr {
        Expr::Ident(col_name) => {
            if !col_types.contains_key(col_name.as_str()) {
                let available: Vec<&str> = col_types.keys().map(String::as_str).collect();
                let suggestion = find_closest_col(col_name, &available).unwrap_or(col_name);
                return Err(format!(
                    "[SchemaError] at {}\n\
                     ─────────────────────────────────────────────\n\
                     Cause   : filter()/withColumn() 에 선언되지 않은 컬럼이 있습니다.\n\
                     Detail  : column '{}' not found in schema\n\
                     Available: {}\n\
                     → Did you mean: col(\"{}\")",
                    source_path,
                    col_name,
                    available.join(", "),
                    suggestion
                )
                .into());
            }
            Ok(())
        }
        Expr::BinOp { lhs, rhs, .. } => {
            validate_expr_columns(lhs, col_types, source_path)?;
            if matches!(rhs.as_ref(), Expr::Ident(_)) {
                validate_expr_columns(rhs, col_types, source_path)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 타입 인식 Polars 표현식 생성 ──────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn to_typed_polars_expr(expr: &Expr, col_types: &HashMap<String, String>) -> String {
    match expr {
        Expr::Ident(s) => format!("col(\"{}\")", s),
        Expr::StringLit(s) => format!("lit(\"{}\")", s),
        Expr::IntLit(n) => format!("lit({}i64)", n),
        Expr::FloatLit(f) => format!("lit({}f64)", f),
        Expr::BoolLit(b) => format!("lit({})", b),
        Expr::BinOp { lhs, op, rhs } => {
            let lhs_is_float = if let Expr::Ident(col_name) = lhs.as_ref() {
                col_types
                    .get(col_name.as_str())
                    .map(|t| t.contains("float"))
                    .unwrap_or(false)
            } else {
                false
            };

            let l = to_typed_polars_expr(lhs, col_types);

            let r = if lhs_is_float {
                match rhs.as_ref() {
                    Expr::IntLit(n) => format!("lit({:.1}f64)", *n as f64),
                    Expr::FloatLit(f) => format!("lit({}f64)", f),
                    other => to_typed_polars_expr(other, col_types),
                }
            } else {
                to_typed_polars_expr(rhs, col_types)
            };

            let op_method = match op {
                BinOpKind::Eq => "eq",
                BinOpKind::NotEq => "neq",
                BinOpKind::Lt => "lt",
                BinOpKind::Gt => "gt",
                BinOpKind::LtEq => "lt_eq",
                BinOpKind::GtEq => "gt_eq",
                // ── 산술 연산자 (v0.16+) ──────────────────────
                BinOpKind::Add => "add",
                BinOpKind::Sub => "sub",
                BinOpKind::Mul => "mul",
                BinOpKind::Div => "div",
            };
            format!("{}.{}({})", l, op_method, r)
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 오타 힌트: 편집 거리 기반 컬럼명 제안 ───────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn find_closest_col<'a>(name: &str, candidates: &[&'a str]) -> Option<&'a str> {
    candidates
        .iter()
        .min_by_key(|&&c| edit_distance(name, c))
        .copied()
}

fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let (m, n) = (a.len(), b.len());
    let mut dp = vec![vec![0usize; n + 1]; m + 1];
    for i in 0..=m {
        dp[i][0] = i;
    }
    for j in 0..=n {
        dp[0][j] = j;
    }
    for i in 1..=m {
        for j in 1..=n {
            dp[i][j] = if a[i - 1] == b[j - 1] {
                dp[i - 1][j - 1]
            } else {
                1 + dp[i - 1][j].min(dp[i][j - 1]).min(dp[i - 1][j - 1])
            };
        }
    }
    dp[m][n]
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 생성된 파일에 포함될 CSV 로더 헬퍼 함수 소스 ──────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

fn emit_csv_loader_fn() -> String {
    r#"/// EUC-KR(CP949) 자동 감지 CSV 로더
/// UTF-8 직접 시도 → 실패 시 EUC-KR 디코딩 (한국 공공데이터 대응)
fn load_csv(file_path: &str) -> Result<DataFrame, Box<dyn std::error::Error>> {
    let raw_bytes = std::fs::read(file_path)?;

    // UTF-8 직접 시도 → 실패 시 EUC-KR(CP949) 디코딩
    let utf8_string = match String::from_utf8(raw_bytes.clone()) {
        Ok(s) => s,
        Err(_) => {
            let (cow, _, _) = EUC_KR.decode(&raw_bytes);
            cow.into_owned()
        }
    };

    let cursor = Cursor::new(utf8_string.into_bytes());
    let df = CsvReadOptions::default()
        .with_infer_schema_length(Some(200))
        .with_parse_options(
            CsvParseOptions::default()
                .with_null_values(Some(NullValues::AllColumnsSingle("-".into()))),
        )
        .into_reader_with_file_handle(cursor)
        .finish()?;

    Ok(df)
}
"#
    .to_string()
}

// ─────────────────────────────────────────────────────────────────────────────
// ── emitter 유닛 테스트 ───────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Lexer;
    use crate::parser::Parser;

    /// 소스 문자열을 파싱한 Program 을 반환한다.
    fn parse(src: &str) -> Program {
        let tokens = Lexer::new(src).tokenize().unwrap();
        Parser::new(tokens).parse().unwrap()
    }

    /// 소스 문자열에 대해 생성된 Rust 소스를 반환한다.
    fn emit(src: &str) -> String {
        let program = parse(src);
        generate_rust_src(&program, "test.xzz").unwrap()
    }

    #[test]
    fn emit_rust_has_polars_imports() {
        let out = emit(
            "type S = { date: string, pm10: float };
             v a = load(\"x.csv\") :: S |> select([date, pm10]);",
        );
        assert!(
            out.contains("use polars::prelude::*;"),
            "polars import 없음"
        );
        assert!(
            out.contains("use encoding_rs::EUC_KR;"),
            "EUC_KR import 없음"
        );
    }

    #[test]
    fn emit_rust_contains_csv_loader() {
        let out = emit(
            "type S = { a: string };
             v p = load(\"x.csv\") :: S;",
        );
        assert!(out.contains("fn load_csv("), "load_csv 헬퍼 없음");
        assert!(out.contains("CsvReadOptions"), "CsvReadOptions 없음");
    }

    #[test]
    fn emit_rust_maps_load_and_collect() {
        let out = emit(
            "type S = { a: string, b: float };
             v p = load(\"x.csv\") :: S |> filter(b > 10) |> mean(\"b\");",
        );
        assert!(out.contains("load_csv("), "load_csv 없음");
        assert!(out.contains(".collect()"), ".collect() 없음");
        assert!(out.contains("mean"), "mean 집계 없음");
    }

    #[test]
    fn emit_rust_emits_burn_for_dl_program() {
        let out = emit(
            "type S = { a: float, y: float };
             model M { Dense(4) -> ReLU() -> Dense(1) }
             v data = load(\"x.csv\") :: S |> train(M, target: \"y\", epochs: 3);",
        );
        assert!(out.contains("use burn::"), "burn import 없음");
        assert!(out.contains("struct M<B: Backend>"), "모델 구조체 없음");
        assert!(out.contains("Adam"), "Adam 옵티마이저 없음");
    }

    #[test]
    fn emit_rust_skips_burn_for_plain_program() {
        let out = emit(
            "type S = { a: string };
             v p = load(\"x.csv\") :: S |> select([a]);",
        );
        assert!(
            !out.contains("use burn::"),
            "DL 없는 프로그램에 burn import 생성됨"
        );
    }

    #[test]
    fn emit_rust_contains_source_comment() {
        let out = emit("type S = { a: string }; v p = load(\"x.csv\") :: S;");
        assert!(out.contains("test.xzz"), "소스 경로 주석 없음");
        assert!(out.contains("Auto-generated by xazzLang"), "헤더 없음");
    }
}
